print("Hello, World!")
x=7
print(x)
print(type(x))
y=("alex")
s=("serrano")
print("alex")
print(type(y))
print(y+" "+s)
print(1,2,3)
print("buen"+" "+"dia")
print(len(s))
print(len(y))
print (8 >5)
print (5>8)
print (8>=8)
print (8==8)
print (8==9)
print (8!=8)
print (8!=9)
print (int("145"))
print (len("nube")<20)
print (len("hola"))
print ("hola"[0])
print (len("hola"))
print ("Alex")
Course = ("Python")
print (Course)
print (type(Course))
a = ("Jo")
b = ("no")
c = ("dormo")
d = ("molt, ")
e = ("poc")
print (a + " " + b + " " + c + " " + d + " " + c)
n1 = (10)
n2 = (15)
print (n1 + n2)
print (str(n1)+str(n2))
print (s + s + s)
kg = (90)
print ("Peso" + " " + (str(kg)) + " " + "quilos")